SELECT REGLANEGOCIOID,
       PARAMETROID,
       DESCRIPCION_PARAMETRO,
       VALOR,
       FECHA_ACTUALIZACION,
       USUARIO
FROM [schema].MTS_HRN_PARAMETROS --<1>
WHERE REGLANEGOCIOID = ?; --<2>