SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR, -- <1>
       OPER.MONTOCNTR,
       OPER.MONTOUSD,
       OPER.MONTO_EFECTIVO,
       CNTE.CONTRATANTERFC,
       OPER.CODOPER
FROM (
         SELECT OPER2.OPERCNTRID,
                OPER2.NUMPOLIZACNTR,
                OPER2.TIPODOCUMENTOID,
                OPER2.TIPOOPERACIONID,
                OPER2.INSTRMONETARIOID,
                OPER2.MONEDAID,
                OPER2.CONTRATANTEID,
                OPER2.AGENTEID,
                OPER2.EMPLEADOID,
                OPER2.SUCURSALID,
                OPER2.PRODUCTOID,
                OPER2.FECHAOPERACIONCNTR,
                OPER2.LINEANEGOCIOID,
                OPER2.MONTOMNCNTR,
                OPER2.MONTOCNTR,
                OPER2.MONTOUSD,
                OPER2.MONTO_EFECTIVO,
                OPER2.CODOPER,
                (SELECT (SUM(DOLARES) / COUNT(1)) -- PARAMETRO DE PORCENTAJE DESVIACION 1.5% --SE QUITA EL % DE DESVIACIÓN
                 FROM (SELECT ROW_NUMBER() OVER (ORDER BY OPE.FECHAOPERACIONCNTR, OPE.OPERCNTRID DESC) NUM,
                              OPE.MONTOMNCNTR                                                          DOLARES
                       FROM SOFOM.MTS_HOPERACIONESCNTR OPE,
                            SOFOM.MTS_CRN_CIERRE CIE1
                       WHERE OPE.FECHAOPERACIONCNTR <= OPER2.FECHAOPERACIONCNTR
                         AND OPE.FECHAOPERACIONCNTR >= CIE1.FECHA_INI_CIERRE
                         AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                         AND OPE.TIPOOPERACIONID = 9  -- REALIZAR CAMBIO PARA QUE SEA PARÁMETRO
                         AND CONTRATANTEID = (SELECT DISTINCT CONTRATANTEID
                                              FROM SOFOM.MTS_HOPERACIONESCNTR HOPE
                                              WHERE HOPE.OPERCNTRID = OPER2.OPERCNTRID)
                         AND OPE.OPERCNTRID <> OPER2.OPERCNTRID) ANALISIS
                 WHERE ANALISIS.NUM <= ?) PROMEDIOOPER -- PARAMETRO NUMERO DE OPERACIONES
         FROM SOFOM.MTS_HOPERACIONESCNTR OPER2,
              SOFOM.MTS_CRN_CIERRE CIE
         WHERE CIE.CIERREID = ? -- PARAMETRO CIERRE
           AND OPER2.FECHAOPERACIONCNTR <= CIE.FECHA_FIN_CIERRE
           AND OPER2.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
           AND OPER2.TIPOOPERACIONID = 9
           AND OPER2.MONTOMNCNTR > ?) OPER, -- PARAMETRO MONTO USD
           AND OPER2.MONTOUSD > ?) OPER, -- PARAMETRO MONTO USD
     SOFOM.MTS_DCONTRATANTE CNTE
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
  AND PROMEDIOOPER IS NOT NULL
  AND OPER.MONTOUSD >= PROMEDIOOPER
  AND OPER.MONTOUSD >= PROMEDIOOPER
  AND OPER.TIPOOPERACIONID = 9
  AND EXISTS(SELECT NULL
             FROM SOFOM.MTS_EXT_PRODUCTOS_CIERRE
             WHERE ID_PROCESO = ? --PARAMETRO ID_PROCESO
               AND PRODUCTID = OPER.PRODUCTOID)
  AND NOT EXISTS(SELECT NULL
                 FROM SOFOM.MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = OPER.CODOPER
                   AND REGLANEGOCIOID = ?)-- NUMERO DE REGLA
ORDER BY OPER.CONTRATANTEID, OPER.FECHAOPERACIONCNTR, OPER.OPERCNTRID;

