-- Evalua las operaciones que superan los 7,500 usd

SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR,
       OPER.MONTOCNTR,
       OPER.MONTO_EFECTIVO -- Este es el monto a considerar expresado en mn, CNTE.CONTRATANTERFC, OPER.CODOPER
FROM SOFOM.MTS_HOPERACIONESCNTR OPER,
     SOFOM.MTS_DCONTRATANTE CNTE,
     SOFOM.MTS_HTIPOS_CAMBIO TIPO,
     SOFOM.MTS_CRN_CIERRE CIER
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
  AND CIER.CIERREID = ?                          -- PARAMETRO CIERRE
  AND OPER.FECHAOPERACIONCNTR <= CIER.FECHA_FIN_CIERRE
  AND OPER.FECHAOPERACIONCNTR >= CIER.FECHA_INI_CIERRE
  AND RIGHT('00' + OPER.INSTRMONETARIOID, 2) = ? -- PARAMETRO INSTRUMENTO MONETARIO
  AND RIGHT('00' + OPER.TIPOOPERACIONID, 2)
    -- ******************
    IN (
--                                 SELECT  RIGHT('00'+ TIPOOPERACIONID, 2)
--                                                   FROM  SOFOM.MTS_DTIPO_OPERACIONES
--                                                  WHERE  APORTACION = 'S'
          ?
          )

  AND (MONTOUSD) > ?                             -- PARAMETRO TRANSACCIONES > 7500 USD EN EFECTIVO
  AND TIPO.MONEDAID = 'USD'
--                     AND TIPO.FECHA = (SELECT   MAX (FECHA)
--                                      FROM   SOFOM.MTS_HTIPOS_CAMBIO
--                                     WHERE   FECHA     <=  CIER.FECHA_FIN_CIERRE
--                                       AND   MONEDAID  =   'USD'
--                                       )
  AND (OPER.CVE_ESTATUS = 'S' OR OPER.CVE_ESTATUS IS NULL)
  AND EXISTS(SELECT NULL
             FROM SOFOM.MTS_EXT_PRODUCTOS_CIERRE
             WHERE ID_PROCESO = ?
               AND PRODUCTID = OPER.PRODUCTOID)
  AND NOT EXISTS(SELECT NULL
                 FROM SOFOM.MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = OPER.CODOPER
                   AND REGLANEGOCIOID = ?)
ORDER BY OPER.CONTRATANTEID, OPER.FECHAOPERACIONCNTR, OPER.OPERCNTRID
