-- RN16 REGLA EVASIÓN DE PARÁMETROS
-- Monto inferior 8000 USD
-- Monto Superior 10000 USD
-- Numero de Operaciones superior a 30
-- Instrumento Monetario 1 (Efectivo)
SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR, -- ESTE ES EL MONTO A CONSIDERAR ESPRESADO EN USD
       OPER.MONTOCNTR,
       OPER.MONTO_EFECTIVO,
       CNTE.CONTRATANTERFC,
       OPER.CODOPER
FROM (SELECT OPER2.OPERCNTRID,
             OPER2.NUMPOLIZACNTR,
             OPER2.TIPODOCUMENTOID,
             OPER2.TIPOOPERACIONID,
             OPER2.INSTRMONETARIOID,
             OPER2.MONEDAID,
             OPER2.CONTRATANTEID,
             OPER2.AGENTEID,
             OPER2.EMPLEADOID,
             OPER2.SUCURSALID,
             OPER2.PRODUCTOID,
             OPER2.FECHAOPERACIONCNTR,
             OPER2.LINEANEGOCIOID,
             OPER2.MONTOMNCNTR,
             OPER2.MONTOCNTR,
             OPER2.MONTO_EFECTIVO,
             OPER2.CODOPER,
             (SELECT COUNT(*) NUM
              FROM [SOFOM].MTS_HOPERACIONESCNTR OPE
              WHERE OPE.CONTRATANTEID = OPER2.CONTRATANTEID
                AND OPE.FECHAOPERACIONCNTR <= OPER2.FECHAOPERACIONCNTR
                AND OPE.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
                AND OPE.INSTRMONETARIOID = OPER2.INSTRMONETARIOID
                AND OPE.MONEDAID = OPER2.MONEDAID
                AND OPE.OPERCNTRID < OPER2.OPERCNTRID
                AND OPE.MONTOMNCNTR > ? -- PARAMETRO MONTO INFERIOR
                AND OPE.MONTOMNCNTR < ? -- PARAMETRO MONTO SUPERIOR
                AND OPE.MONEDAID = 'USD'
                AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                AND OPE.TIPOOPERACIONID IN
                    (SELECT TIPOOPERACIONID
                     FROM [SOFOM].MTS_DTIPO_OPERACIONES
                          -- WHERE DS_TIPO_OPERACION LIKE ?) -- TIPO OPERACIONES DEPOSITO validar como se pasa el parámetro para modifcarlo
                     WHERE APORTACION = 'S')
             ) REGS,
             (SELECT SUM(OPE.MONTOMNCNTR) SUMA
              FROM [SOFOM].MTS_HOPERACIONESCNTR OPE
              WHERE OPE.CONTRATANTEID = OPER2.CONTRATANTEID
                AND OPE.FECHAOPERACIONCNTR <= OPER2.FECHAOPERACIONCNTR
                AND OPE.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
                AND OPE.INSTRMONETARIOID = OPER2.INSTRMONETARIOID
                AND OPE.MONEDAID = OPER2.MONEDAID
                AND OPE.OPERCNTRID < OPER2.OPERCNTRID
                AND OPE.MONEDAID = 'USD'
                AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                AND OPE.TIPOOPERACIONID IN
                    (SELECT TIPOOPERACIONID
                     FROM [SOFOM].MTS_DTIPO_OPERACIONES
                          -- WHERE DS_TIPO_OPERACION LIKE ?) -- TIPO OPERACIONES DEPOSITO validar como se pasa el parámetro para modifcarlo
                     WHERE APORTACION = 'S')
             ) SUMA_REGS
      FROM [SOFOM].MTS_HOPERACIONESCNTR OPER2,
           [SOFOM].MTS_CRN_CIERRE CIE
      WHERE CIE.CIERREID = ?           -- PARAMETRO CIERRE
        AND OPER2.FECHAOPERACIONCNTR <= CIE.FECHA_FIN_CIERRE
        AND OPER2.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
        AND (OPER2.CVE_ESTATUS = 'S' OR OPER2.CVE_ESTATUS IS NULL)
        AND OPER2.TIPOOPERACIONID IN
            (SELECT TIPOOPERACIONID
             FROM [SOFOM].MTS_DTIPO_OPERACIONES
                  --WHERE DS_TIPO_OPERACION LIKE ?) -- TIPO OPERACIONES DEPOSITO validar como se pasa el parámetro para modifcarlo
             WHERE APORTACION = 'S')
        AND OPER2.INSTRMONETARIOID = ? -- EFECTIVO
        AND OPER2.MONEDAID = 'USD') OPER,
     [SOFOM].MTS_DCONTRATANTE CNTE
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID -- MONEDA DOLAR
  AND SUMA_REGS > ?                           -- PARAMETRO MONTO INFERIOR
  AND SUMA_REGS < ?                           -- PARAMETRO MONTO SUPERIOR
  AND REGS > ?                                -- NUMERO DE OPERACIONES
  AND EXISTS
    (SELECT NULL
     FROM [SOFOM].MTS_EXT_PRODUCTOS_CIERRE
     WHERE ID_PROCESO = ? --PARAMETRO ID_PROCESO
       AND PRODUCTID = OPER.PRODUCTOID)
  AND NOT EXISTS
    (SELECT NULL
     FROM [SOFOM].MTS_HRN_CASOS_REGLAS
     WHERE CODOPER = OPER.CODOPER
       AND REGLANEGOCIOID = ?)                -- NUMERO DE REGLA
ORDER BY OPER.CONTRATANTEID, Oper.FECHAOPERACIONCNTR, OPER.OPERCNTRID;
