SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR, -- ESTE ES EL MONTO A CONSIDERAR ESPRESADO EN USD
       OPER.MONTOCNTR,
       OPER.MONTO_EFECTIVO,
       CNTE.CONTRATANTERFC,
       OPER.CODOPER
FROM SOFOM.MTS_HOPERACIONESCNTR OPER,
     SOFOM.MTS_CRN_CIERRE CIE,
     SOFOM.MTS_DCONTRATANTE CNTE
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
  AND CIE.CIERREID = ?         -- PARAMETRO CIERRE
  AND OPER.FECHAOPERACIONCNTR <= CIE.FECHA_FIN_CIERRE
  AND OPER.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
  AND (OPER.CVE_ESTATUS = 'S' OR OPER.CVE_ESTATUS IS NULL)
-- 				      AND OPER.TIPOOPERACIONID IN (SELECT TIPOOPERACIONID
-- 													FROM SOFOM.MTS_DTIPO_OPERACIONES
-- 												   WHERE  APORTACION = 'S')
  AND OPER.TIPOOPERACIONID IN (?)
  AND MONTOUSD > ?             -- NUMERO DE OPERACIONES
--   AND EXISTS
--     (SELECT NULL
--      FROM SOFOM.MTS_EXT_PRODUCTOS_CIERRE
--      WHERE ID_PROCESO = ? --PARAMETRO ID_PROCESO
--        AND PRODUCTID = OPER.PRODUCTOID)
  AND NOT EXISTS
    (SELECT NULL
     FROM SOFOM.MTS_HRN_CASOS_REGLAS
     WHERE CODOPER = OPER.CODOPER
       AND REGLANEGOCIOID = ?) -- NUMERO DE REGLA
ORDER BY OPER.CONTRATANTEID, Oper.FECHAOPERACIONCNTR, OPER.OPERCNTRID

