/**************************************************************************
REGLA 243
Alerta de Inusualidad - Cambio en el Perfil Transaccional
***************************************************************************/
SELECT ?                         ANIO,
       ?                         MES,
       KPER.CONTRATANTECD,
       KPER.CVE_ROL,
       KPER.NOMBRES,
       KPER.APELLIDO_PATERNO,
       KPER.APELLIDO_MATERNO,
       KPER.DS_RAZON_SOCIAL,
       KPER.CURP,
       KPER.RFC                  CONTRATANTERFC,
       KPER.CVE_TIPO_FISICA_MORAL,
       KPER.CVE_NIVEL_RIESGO,
       NO_OPERACIONES_DEPOSITO,
       ACT_NO_TOT_DEPOSITOS,
       IMP_MONTO_ESTIMADO_TRX_DEPOSITO,
       ACT_IMP_MONTO_TOT_DEPOSITOS,
       NO_OPERACIONES_RETIRO,
       ACT_NO_TOT_RETIROS,
       IMP_MONTO_ESTIMADO_TRX_RETIRO,
       ACT_IMP_MONTO_TOT_RETIROS,
       NO_PAGOS_CREDITO_MENSUAL,
       ACT_NO_TOT_APORTACIONES,
       IMP_MONTO_PAGOS_CREDITO_MENSUAL,
       ACT_IMP_MONTO_TOT_APORTACIONES
           - -PERFIL.
           FROM SOFOM.MTS_VL_KYC_ANALISIS_PERFIL PERFIL,
       SOFOM.MTS_VL_KYC_PERSONAS KPER
WHERE YEAR = ? /* SE OBTIENE A PARTIR DE LA FECHA FIN DE CIERRE */
  AND MONTH = ?/*  SE OBTIENE A PARTIR DE LA FECHA FIN DE CIERRE */
  AND KPER.CONTRATANTECD = PERFIL.CONTRATANTECD
  AND KPER.CVE_ROL = 'CL'
  AND KPER.CVE_TIPO_FISICA_MORAL IN (?) -- -- PARAMETRO DE TIPO DE PERSONAS
-- 					AND	 CHARINDEX(KPER.CVE_NIVEL_RIESGO,  ? ) > 0  -- PARAMETO NIVEL DE RIESGO
  AND KPER.CVE_NIVEL_RIESGO in (?)      -- PARAMETO NIVEL DE RIESGO   -------- VALIDAR CAMBIO A INT ------
  AND ((((cast(NO_OPERACIONES_DEPOSITO AS DECIMAL) * 1.#percent) - ACT_NO_TOT_DEPOSITOS) < 0 and NO_OPERACIONES_DEPOSITO > 0)  OR
    (((cast(IMP_MONTO_ESTIMADO_TRX_DEPOSITO AS DECIMAL) * 1.#percent) - ACT_IMP_MONTO_TOT_DEPOSITOS)   < 0 AND IMP_MONTO_ESTIMADO_TRX_DEPOSITO > 0) OR
					    (((cast(NO_OPERACIONES_RETIRO AS DECIMAL) * 1.#percent) - ACT_NO_TOT_RETIROS)  < 0  AND NO_OPERACIONES_RETIRO > 0 ) OR
					  	(((cast(IMP_MONTO_ESTIMADO_TRX_RETIRO AS DECIMAL) * 1.#percent) - ACT_IMP_MONTO_TOT_RETIROS) <  0  AND IMP_MONTO_ESTIMADO_TRX_RETIRO > 0  )
					         OR
					    (((CAST(NO_PAGOS_CREDITO_MENSUAL AS DECIMAL) * 1.#percent) - ACT_NO_TOT_APORTACIONES)  < 0  AND NO_PAGOS_CREDITO_MENSUAL > 0  )  OR
					    (((cast(IMP_MONTO_PAGOS_CREDITO_MENSUAL AS DECIMAL) * 1.#percent) - ACT_IMP_MONTO_TOT_APORTACIONES) <  0  AND IMP_MONTO_PAGOS_CREDITO_MENSUAL > 0  ))

