-- 200a Regla inusual STP PEROSONAS 02, 104 - Moral - Centros de costo
DECLARE @NUMERO_OPERACIONES AS INT = ?;
-- Este valor cambia dependiendo del tipo de persona.
DECLARE @MONTO_USD AS VARCHAR = ?;
-- Los tipos de operaciones manejados se enecuntran en el catálogo
-- DECLARE @TIPO_OPERACION AS VARCHAR = ?;
DECLARE @TIPO_OPERACION AS VARCHAR = '(01, 02)';
DECLARE @TIPO_PERSONA AS VARCHAR = ?;
-- Número de días de un mes calendario
DECLARE @NUM_DIAS_ANALISIS AS VARCHAR = ?;
DECLARE @ID_CIERRE AS VARCHAR = ?;
DECLARE @ID_REGLA AS INT = ?;

SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR, 
       OPER.MONTOCNTR,
       OPER.MONTOUSD,
       OPER.MONTO_EFECTIVO,
       CNTE.CONTRATANTERFC,
       OPER.CODOPER
FROM (
         SELECT OPER2.OPERCNTRID,
                OPER2.NUMPOLIZACNTR,
                OPER2.TIPODOCUMENTOID,
                OPER2.TIPOOPERACIONID,
                OPER2.INSTRMONETARIOID,
                OPER2.MONEDAID,
                OPER2.CONTRATANTEID,
                OPER2.AGENTEID,
                OPER2.EMPLEADOID,
                OPER2.SUCURSALID,
                OPER2.PRODUCTOID,
                OPER2.FECHAOPERACIONCNTR,
                OPER2.LINEANEGOCIOID,
                OPER2.MONTOMNCNTR,
                OPER2.MONTOCNTR,
                OPER2.MONTOUSD,
                OPER2.MONTO_EFECTIVO,
                OPER2.CODOPER,

                (SELECT (SUM(MONTO_USD)) -- PARAMETRO DE PORCENTAJE DESVIACION 1.5% --SE QUITA EL % DE DESVIACIÓN
                 FROM (SELECT ROW_NUMBER() OVER (ORDER BY OPE.FECHAOPERACIONCNTR, OPE.OPERCNTRID DESC) NUM,
                              OPE.MONTOUSD                                                          MONTO_USD
                       FROM SOFOM.MTS_HOPERACIONESCNTR OPE,
                            SOFOM.MTS_CRN_CIERRE CIE1
                       WHERE OPE.FECHAOPERACIONCNTR <= OPER2.FECHAOPERACIONCNTR
                         AND OPE.FECHAOPERACIONCNTR >= DATEADD(DAY, @NUM_DIAS_ANALISIS, CIE1.FECHA_INI_CIERRE)
                         AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                         AND OPE.TIPOOPERACIONID IN (@TIPO_OPERACION)  -- REALIZAR CAMBIO PARA QUE SEA PARÁMETRO
                         AND CONTRATANTEID = (SELECT DISTINCT CONTRATANTEID
                                              FROM SOFOM.MTS_HOPERACIONESCNTR HOPE
                                              WHERE HOPE.OPERCNTRID = OPER2.OPERCNTRID)
                         AND OPE.OPERCNTRID <> OPER2.OPERCNTRID) ANALISIS
                 WHERE ANALISIS.NUM <= @NUMERO_OPERACIONES) MONTO_PROMEDIO_OPERADO -- PARAMETRO NUMERO DE OPERACIONES

         FROM SOFOM.MTS_HOPERACIONESCNTR OPER2,
              SOFOM.MTS_CRN_CIERRE CIE
         WHERE CIE.CIERREID = @ID_CIERRE -- PARAMETRO CIERRE
           AND OPER2.FECHAOPERACIONCNTR <= CIE.FECHA_FIN_CIERRE
           AND OPER2.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
           AND OPER2.TIPOOPERACIONID IN (@TIPO_OPERACION)
           AND OPER2.MONTOUSD > @MONTO_USD) OPER, -- PARAMETRO MONTO USD
     SOFOM.MTS_DCONTRATANTE CNTE
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
  AND MONTO_PROMEDIO_OPERADO IS NOT NULL
  AND OPER.MONTOUSD >= MONTO_PROMEDIO_OPERADO
  AND OPER.TIPOOPERACIONID IN (@TIPO_OPERACION)
  AND CNTE.TIPOPERSONAFISCALID IN (@TIPO_PERSONA)
  AND NOT EXISTS(SELECT NULL
                 FROM SOFOM.MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = OPER.CODOPER
                   AND REGLANEGOCIOID = @ID_REGLA) -- NUMERO DE REGLA
ORDER BY OPER.CONTRATANTEID, OPER.FECHAOPERACIONCNTR, OPER.OPERCNTRID;

-- Revisión de los parámetros con Ana, los montos son en Dolares




-- 200b Regla inusual STP PEROSONAS 103 Personas físicas
DECLARE @NUMERO_OPERACIONES AS INT = ?;
-- Este valor cambia dependiendo del tipo de persona.
DECLARE @MONTO_USD AS VARCHAR = ?;
-- Los tipos de operaciones manejados se enecuntran en el catálogo
-- DECLARE @TIPO_OPERACION AS VARCHAR = ?;
DECLARE @TIPO_OPERACION AS VARCHAR = '(01, 02)';
DECLARE @TIPO_PERSONA AS VARCHAR = ?;
-- Número de días de un mes calendario
DECLARE @NUM_DIAS_ANALISIS AS VARCHAR = ?;
DECLARE @ID_CIERRE AS VARCHAR = ?;
DECLARE @ID_REGLA AS INT = ?;

SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR, 
       OPER.MONTOCNTR,
       OPER.MONTOUSD,
       OPER.MONTO_EFECTIVO,
       CNTE.CONTRATANTERFC,
       OPER.CODOPER
FROM (
         SELECT OPER2.OPERCNTRID,
                OPER2.NUMPOLIZACNTR,
                OPER2.TIPODOCUMENTOID,
                OPER2.TIPOOPERACIONID,
                OPER2.INSTRMONETARIOID,
                OPER2.MONEDAID,
                OPER2.CONTRATANTEID,
                OPER2.AGENTEID,
                OPER2.EMPLEADOID,
                OPER2.SUCURSALID,
                OPER2.PRODUCTOID,
                OPER2.FECHAOPERACIONCNTR,
                OPER2.LINEANEGOCIOID,
                OPER2.MONTOMNCNTR,
                OPER2.MONTOCNTR,
                OPER2.MONTOUSD,
                OPER2.MONTO_EFECTIVO,
                OPER2.CODOPER,

                (SELECT (SUM(MONTO_USD)) -- PARAMETRO DE PORCENTAJE DESVIACION 1.5% --SE QUITA EL % DE DESVIACIÓN
                 FROM (SELECT ROW_NUMBER() OVER (ORDER BY OPE.FECHAOPERACIONCNTR, OPE.OPERCNTRID DESC) NUM,
                              OPE.MONTOUSD                                                          MONTO_USD
                       FROM SOFOM.MTS_HOPERACIONESCNTR OPE,
                            SOFOM.MTS_CRN_CIERRE CIE1
                       WHERE OPE.FECHAOPERACIONCNTR <= OPER2.FECHAOPERACIONCNTR
                         AND OPE.FECHAOPERACIONCNTR >= DATEADD(DAY, @NUM_DIAS_ANALISIS, CIE1.FECHA_INI_CIERRE)
                         AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                         AND OPE.TIPOOPERACIONID IN (@TIPO_OPERACION)  -- REALIZAR CAMBIO PARA QUE SEA PARÁMETRO
                         AND CONTRATANTEID = (SELECT DISTINCT CONTRATANTEID
                                              FROM SOFOM.MTS_HOPERACIONESCNTR HOPE
                                              WHERE HOPE.OPERCNTRID = OPER2.OPERCNTRID)
                         AND OPE.OPERCNTRID <> OPER2.OPERCNTRID) ANALISIS
                 WHERE ANALISIS.NUM <= @NUMERO_OPERACIONES) MONTO_PROMEDIO_OPERADO -- PARAMETRO NUMERO DE OPERACIONES

         FROM SOFOM.MTS_HOPERACIONESCNTR OPER2,
              SOFOM.MTS_CRN_CIERRE CIE
         WHERE CIE.CIERREID = @ID_CIERRE -- PARAMETRO CIERRE
           AND OPER2.FECHAOPERACIONCNTR <= CIE.FECHA_FIN_CIERRE
           AND OPER2.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
           AND OPER2.TIPOOPERACIONID IN (@TIPO_OPERACION)
           AND OPER2.MONTOUSD > @MONTO_USD) OPER, -- PARAMETRO MONTO USD
     SOFOM.MTS_DCONTRATANTE CNTE
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
  AND MONTO_PROMEDIO_OPERADO IS NOT NULL
  AND OPER.MONTOUSD >= MONTO_PROMEDIO_OPERADO
  AND OPER.TIPOOPERACIONID IN (@TIPO_OPERACION)
  AND CNTE.TIPOPERSONAFISCALID IN (@TIPO_PERSONA)
  AND NOT EXISTS(SELECT NULL
                 FROM SOFOM.MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = OPER.CODOPER
                   AND REGLANEGOCIOID = @ID_REGLA) -- NUMERO DE REGLA
ORDER BY OPER.CONTRATANTEID, OPER.FECHAOPERACIONCNTR, OPER.OPERCNTRID;
