-- Evalua las operaciones que superan los 7,500 usd

DECLARE @MONTO_USD AS VARCHAR = 7500;
DECLARE @TIPO_OPERACION AS VARCHAR = '(01, 02)';
DECLARE @ID_CIERRE AS VARCHAR = ?;
DECLARE @ID_REGLA AS INT = ?;
DECLARE @INSTRUMENTO_MONETARIO AS INT = ?;

SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR,
       OPER.MONTOCNTR,
       OPER.MONTO_EFECTIVO -- Este es el monto a considerar expresado en mn, CNTE.CONTRATANTERFC, OPER.CODOPER
FROM SOFOM.MTS_HOPERACIONESCNTR OPER,
     SOFOM.MTS_DCONTRATANTE CNTE,
     SOFOM.MTS_HTIPOS_CAMBIO TIPO,
     SOFOM.MTS_CRN_CIERRE CIER
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
  AND CIER.CIERREID = @ID_CIERRE                                         -- PARAMETRO CIERRE
  AND OPER.FECHAOPERACIONCNTR <= CIER.FECHA_FIN_CIERRE
  AND OPER.FECHAOPERACIONCNTR >= CIER.FECHA_INI_CIERRE
--   AND RIGHT('00' + OPER.INSTRMONETARIOID, 2) in (@INSTRUMENTO_MONETARIO) -- PARAMETRO INSTRUMENTO MONETARIO
  AND RIGHT('00' + OPER.INSTRMONETARIOID, 2) in (3) -- PARAMETRO INSTRUMENTO MONETARIO
  AND RIGHT('00' + OPER.TIPOOPERACIONID, 2) IN (@TIPO_OPERACION)
  AND (MONTOUSD) > @MONTO_USD                                            -- PARAMETRO TRANSACCIONES > 7500 USD EN EFECTIVO
  AND (OPER.CVE_ESTATUS = 'S' OR OPER.CVE_ESTATUS IS NULL)
  AND NOT EXISTS(SELECT NULL
                 FROM SOFOM.MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = OPER.CODOPER
                   AND REGLANEGOCIOID = 208)
--                    AND REGLANEGOCIOID = @ID_REGLA)
ORDER BY OPER.CONTRATANTEID, OPER.FECHAOPERACIONCNTR, OPER.OPERCNTRID
