-- PIVOTES
-- Se inserta en hrn_casos,
SELECT OP.OPERCNTRID,
       OP.NUMPOLIZACNTR,
       OP.TIPODOCUMENTOID,
       OP.TIPOOPERACIONID,
       OP.INSTRMONETARIOID,
       OP.MONEDAID,
       OP.CONTRATANTEID,
       OP.AGENTEID,
       OP.EMPLEADOID,
       OP.SUCURSALID,
       OP.PRODUCTOID,
       OP.FECHAOPERACIONCNTR,
       OP.LINEANEGOCIOID,
       OP.MONTOMNCNTR, -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
       OP.MONTOCNTR,
       OP.MONTO_EFECTIVO,
       OP.CONTRATANTECD          CONTRATANTERFC,
       OP.CODOPER,
       ISNULL(OP.MONTOUSD, 0) AS MONTOUSD,
       PIVOTE.NUM_OPERACIONES,
       PIVOTE.MONTOUSD_TOTAL,
       PIVOTE.MONTOMN_TOTAL,
       PIVOTE.RFC_BENEFICIARIO,
       OP.CUENTA_BENEFICIARIO
FROM TD.MTS_HOPERACIONESCNTR OP,
     (
         SELECT MAX(OPERCNTRID)  OPERCNTRID,
                OPE.CONTRATANTEID,
                OPE.RFC_BENEFICIARIO,
                COUNT(*)         NUM_OPERACIONES,
                SUM(MONTOMNCNTR) MONTOMN_TOTAL,
                SUM(MONTOUSD)    MONTOUSD_TOTAL
         FROM (SELECT OPERCNTRID,
                      CVE_TIPO_ORDEN,
                      CONTRATANTEID,
                      RFC_BENEFICIARIO,
                      MONTOMNCNTR,
                      MONTOUSD,
                      FECHAOPERACIONCNTR
               FROM TD.MTS_HOPERACIONESCNTR WITH (INDEX ([IDX_FECHAOPERACION]))
               WHERE FECHAOPERACIONCNTR BETWEEN '2020-06-01 00:00:00:000' AND '2020-06-30 23:59:59.999'
                 AND RIGHT('00' + INSTRMONETARIOID, 2) IN ('03') -- PARAMETRO INSTRUMENTO MONETARIO EFECTIVO
                 AND RIGHT('00' + TIPOOPERACIONID, 2) IN ('01', '02')
                 AND RFC_BENEFICIARIO IS NOT NULL
                  --AND   CVE_TIPO_ORDEN = 'R'
                  --AND   CONTRATANTEID = 56868
              ) OPE
                  JOIN TD.MTS_DCONTRATANTE CNT
                       ON CNT.CONTRATANTEID = OPE.CONTRATANTEID AND CNT.TIPOPERSONAFISCALID IN (2, 104)
         GROUP BY OPE.CONTRATANTEID, OPE.RFC_BENEFICIARIO
         HAVING SUM(OPE.MONTOUSD) > 5000
     ) PIVOTE
WHERE OP.OPERCNTRID = PIVOTE.OPERCNTRID





-- DETALLE
SELECT OP.OPERCNTRID,
       OP.CONTRATANTECD,
       OP.NUMPOLIZACNTR,
       OP.TIPODOCUMENTOID,
       OP.TIPOOPERACIONID,
       OP.INSTRMONETARIOID,
       OP.MONEDAID,
       OP.CONTRATANTEID,
       OP.AGENTEID,
       OP.EMPLEADOID,
       OP.SUCURSALID,
       OP.PRODUCTOID,
       OP.FECHAOPERACIONCNTR,
       OP.LINEANEGOCIOID,
       OP.MONTOMNCNTR, -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
       OP.MONTOCNTR,
       OP.MONTO_EFECTIVO,
       OP.CONTRATANTECD               CONTRATANTERFC,
       OP.CODOPER,
       OP.MONTOMNCNTR,
       ISNULL(DETALLE.MONTOUSD, 0) AS MONTOUSD,
       OP.MONTOUSD,
       DETALLE.RFC_BENEFICIARIO,
       OP.CUENTA_BENEFICIARIO
FROM TD.MTS_HOPERACIONESCNTR OP,
     (
         SELECT OPE.OPERCNTRID, OPE.CONTRATANTEID, RFC_BENEFICIARIO, OPE.MONTOMNCNTR, OPE.MONTOUSD
         FROM (SELECT OPERCNTRID,
                      CVE_TIPO_ORDEN,
                      CONTRATANTEID,
                      RFC_BENEFICIARIO,
                      MONTOMNCNTR,
                      MONTOUSD,
                      FECHAOPERACIONCNTR
               FROM TD.MTS_HOPERACIONESCNTR WITH (INDEX ([IDX_FECHAOPERACION]))
               WHERE FECHAOPERACIONCNTR BETWEEN '2020-06-01 00:00:00:000' AND '2020-06-30 23:59:59.999'
                 AND RIGHT('00' + INSTRMONETARIOID, 2) IN ('03') -- PARAMETRO INSTRUMENTO MONETARIO EFECTIVO
                 AND RIGHT('00' + TIPOOPERACIONID, 2) IN ('01', '02')
                 AND RFC_BENEFICIARIO IS NOT NULL
                 --AND   CVE_TIPO_ORDEN = 'R'
                 AND CONTRATANTEID = 56868                       -- ?
                 AND RFC_BENEFICIARIO = '' -- ?
              ) OPE
                  JOIN TD.MTS_DCONTRATANTE CNT
                       ON CNT.CONTRATANTEID = OPE.CONTRATANTEID AND CNT.TIPOPERSONAFISCALID IN (2, 104)
     ) DETALLE
WHERE OP.OPERCNTRID = DETALLE.OPERCNTRID
ORDER BY OP.CONTRATANTEID, OP.OPERCNTRID DESC;

select *
from TD.DATABASECHANGELOG;



