-- RN16 REGLA EVASIÓN DE PARÁMETROS
-- Monto inferior 8000 USD
-- Monto Superior 10000 USD
-- Numero de Operaciones superior a 30
-- Instrumento Monetario 1 (Efectivo)

DECLARE @MONTO_SUPERIOR AS VARCHAR = ''
DECLARE @MONTO_INFERIOR AS VARCHAR = ''
DECLARE @TIPO_OPERACION AS VARCHAR = ''
DECLARE @NUM_OPERACIONES AS VARCHAR = ''
DECLARE @ID_CIERRE AS VARCHAR = ?;
DECLARE @ID_REGLA AS INT = ?;
DECLARE @INSTRUMENTO_MONETARIO AS INT = ?;


SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR, -- ESTE ES EL MONTO A CONSIDERAR ESPRESADO EN USD
       OPER.MONTOCNTR,
       OPER.MONTO_EFECTIVO,
       CNTE.CONTRATANTERFC,
       OPER.CODOPER
FROM (SELECT OPER2.OPERCNTRID,
             OPER2.NUMPOLIZACNTR,
             OPER2.TIPODOCUMENTOID,
             OPER2.TIPOOPERACIONID,
             OPER2.INSTRMONETARIOID,
             OPER2.MONEDAID,
             OPER2.CONTRATANTEID,
             OPER2.AGENTEID,
             OPER2.EMPLEADOID,
             OPER2.SUCURSALID,
             OPER2.PRODUCTOID,
             OPER2.FECHAOPERACIONCNTR,
             OPER2.LINEANEGOCIOID,
             OPER2.MONTOMNCNTR,
             OPER2.MONTOCNTR,
             OPER2.MONTO_EFECTIVO,
             OPER2.CODOPER,
             (SELECT COUNT(1) NUM
              FROM [SOFOM].MTS_HOPERACIONESCNTR OPE
              WHERE OPE.CONTRATANTEID = OPER2.CONTRATANTEID
                AND OPE.FECHAOPERACIONCNTR <= OPER2.FECHAOPERACIONCNTR
                AND OPE.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
                AND OPE.INSTRMONETARIOID = OPER2.INSTRMONETARIOID
                AND OPE.MONEDAID = OPER2.MONEDAID
                AND OPE.OPERCNTRID < OPER2.OPERCNTRID
                AND OPE.MONTOUSD > @MONTO_INFERIOR -- PARAMETRO MONTO INFERIOR
                AND OPE.MONTOUSD < @MONTO_SUPERIOR -- PARAMETRO MONTO SUPERIOR
                AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                AND OPE.TIPOOPERACIONID IN (@TIPO_OPERACION)
             ) REGS,
             (SELECT SUM(OPE.MONTOUSD) SUMA
              FROM [SOFOM].MTS_HOPERACIONESCNTR OPE
              WHERE OPE.CONTRATANTEID = OPER2.CONTRATANTEID
                AND OPE.FECHAOPERACIONCNTR <= OPER2.FECHAOPERACIONCNTR
                AND OPE.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
                AND OPE.INSTRMONETARIOID = OPER2.INSTRMONETARIOID
                AND OPE.MONEDAID = OPER2.MONEDAID
                AND OPE.OPERCNTRID < OPER2.OPERCNTRID
                AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                AND OPE.TIPOOPERACIONID IN (@TIPO_OPERACION)
             ) SUMA_REGS
      FROM [SOFOM].MTS_HOPERACIONESCNTR OPER2,
           [SOFOM].MTS_CRN_CIERRE CIE
      WHERE CIE.CIERREID = @ID_CIERRE -- PARAMETRO CIERRE
        AND OPER2.FECHAOPERACIONCNTR <= CIE.FECHA_FIN_CIERRE
        AND OPER2.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE
        AND (OPER2.CVE_ESTATUS = 'S' OR OPER2.CVE_ESTATUS IS NULL)
        AND OPER2.TIPOOPERACIONID IN (@TIPO_OPERACION)
        AND OPER2.INSTRMONETARIOID IN (@INSTRUMENTO_MONETARIO) -- EFECTIVO
     ) OPER,
     [SOFOM].MTS_DCONTRATANTE CNTE
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID      -- MONEDA DOLAR
  AND SUMA_REGS > @MONTO_INFERIOR                  -- PARAMETRO MONTO INFERIOR
  AND SUMA_REGS < @MONTO_SUPERIOR                  -- PARAMETRO MONTO SUPERIOR
  AND REGS > @NUM_OPERACIONES                      -- NUMERO DE OPERACIONES
  AND NOT EXISTS(SELECT NULL
                 FROM [SOFOM].MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = OPER.CODOPER
                   AND REGLANEGOCIOID = @ID_REGLA) -- NUMERO DE REGLA
ORDER BY OPER.CONTRATANTEID, Oper.FECHAOPERACIONCNTR, OPER.OPERCNTRID;
                