-- 217 OPERACIONES FRACCIONADAS
-- detectar operaciones que intentan evadir la regla relaevante aplicando
-- El parámetro para discriminar las operaciones que no se evaluarán [Traspaso Final y Fonde]
-- Este parámetro se agrega en la subquery de la suma y en el query principal

declare @NUM_DIAS_ANALISIS AS INT = 3
-- Este parámetro usar como lista IN (01, 02)
declare @TIPO_OPERACION AS VARCHAR = '01'
declare @ID_CIERRE AS VARCHAR = '01'
declare @NUM_TRANSACCIONES_PERMITIDAS AS VARCHAR = '01'
declare @REGLA_ID AS VARCHAR = '01'
declare @MONTO_USD AS VARCHAR = '01'
declare @INSTRUMENTO_MONERTARIO AS VARCHAR = '01'
declare @NUMERO_DIAS_CALENDARIO AS VARCHAR = '01'

--
-- DECLARE @ExcludedList VARCHAR(MAX)
--
-- SET @ExcludedList = '3,4,22,6014'
-- declare @sql nvarchar(Max)
-- Set @sql='SELECT * FROM [A] WHERE Id NOT IN ('+@ExcludedList+')'
-- exec sp_executesql @sql


SELECT OPE.OPERCNTRID
     , OPE.MONTOUSD
     , OPE.NUMPOLIZACNTR
     , OPE.TIPODOCUMENTOID
     , OPE.TIPOOPERACIONID
     , OPE.INSTRMONETARIOID
     , OPE.MONEDAID
     , OPE.CONTRATANTEID
     , OPE.AGENTEID
     , OPE.EMPLEADOID
     , OPE.SUCURSALID
     , OPE.PRODUCTOID
     , OPE.FECHAOPERACIONCNTR
     , OPE.LINEANEGOCIOID
     , OPE.MONTOMNCNTR
     , OPE.MONTOCNTR
     , OPE.MONTO_EFECTIVO -- Considera esta columna que está en pesos pero aquí se hace la conversión a usd
     , OPE.CONTRATANTERFC
     , OPE.CODOPER
FROM (SELECT OPER.OPERCNTRID
           , OPER.CONTRATANTECD
           , OPER.NUMPOLIZACNTR
           , OPER.TIPODOCUMENTOID
           , OPER.TIPOOPERACIONID
           , OPER.INSTRMONETARIOID
           , OPER.MONEDAID
           , OPER.CONTRATANTEID
           , OPER.AGENTEID
           , OPER.EMPLEADOID
           , OPER.SUCURSALID
           , OPER.PRODUCTOID
           , OPER.FECHAOPERACIONCNTR
           , OPER.LINEANEGOCIOID
           , OPER.MONTOMNCNTR
           , OPER.MONTOCNTR
           , OPER.MONTO_EFECTIVO -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
           , CNTE.CONTRATANTERFC
           , OPER.CODOPER
           -- Toma la fecha fin de cierre y un mes hacia atras ejemplo 30 de mayo = 30 de junio
           , (SELECT SUM(ISNULL((HOPER.MONTOUSD), 0)) AS MONTO -- SE CONVIERTEN LOS PESOS A USD
              FROM SOFOM.MTS_HOPERACIONESCNTR HOPER,
                   SOFOM.MTS_CRN_CIERRE NCIER
              WHERE NCIER.CIERREID = CIERRE.CIERREID
                AND HOPER.FECHAOPERACIONCNTR <= NCIER.FECHA_FIN_CIERRE
                AND HOPER.FECHAOPERACIONCNTR >=
                    DATEADD(day, -@NUMERO_DIAS_CALENDARIO, NCIER.FECHA_FIN_CIERRE) -- A UN MES CALENDARIO
                AND RIGHT('00' + HOPER.INSTRMONETARIOID, 2) = RIGHT('00' + OPER.INSTRMONETARIOID, 2)
                AND RIGHT('00' + HOPER.TIPOOPERACIONID, 2) = RIGHT('00' + OPER.TIPOOPERACIONID, 2)
                AND HOPER.CONTRATANTEID = OPER.CONTRATANTEID
                -- and discrimiarn fondeo y traspaso final
              GROUP BY HOPER.CONTRATANTEID) MONTOUSD
      FROM SOFOM.MTS_HOPERACIONESCNTR OPER,
           SOFOM.MTS_DCONTRATANTE CNTE,
           SOFOM.MTS_CRN_CIERRE CIERRE
      WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
        AND CIERRE.CIERREID = @ID_CIERRE                                        -- PARAMETRO CIERRE
        AND OPER.FECHAOPERACIONCNTR <= CIERRE.FECHA_FIN_CIERRE
        AND OPER.FECHAOPERACIONCNTR >=
            DATEADD(DAY, -@NUMERO_DIAS_CALENDARIO, CIERRE.FECHA_FIN_CIERRE)     -- 30 ES POR PARAMETRO
        AND RIGHT('00' + OPER.INSTRMONETARIOID, 2) IN (@INSTRUMENTO_MONERTARIO) -- PARAMETRO INSTRUMENTO MONETARIO EFECTIVO
        AND RIGHT('00' + OPER.TIPOOPERACIONID, 2) IN (@TIPO_OPERACION)
     ) OPE
WHERE OPE.MONTOUSD > @MONTO_USD -- PARAMETRO MONTO 7500 USD
  AND NOT EXISTS(SELECT NULL
                 FROM SOFOM.MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = OPE.CODOPER
                   AND REGLANEGOCIOID = @REGLA_ID)
ORDER BY OPE.CONTRATANTEID, OPE.FECHAOPERACIONCNTR, OPE.OPERCNTRID


-- Comparación del numero de operaciones del dia analizado vs el promedio de operaciones apattir e la fecha de inicio de cierre hasta el final
-- de la fecha de operacion analizada

-- Numero de operaciones que revasen las operaciones permitidas en un mes

-- PARAMETROS REGLA  v1.1
-- Porcentaje desviacion
-- Numero de Dias:30
-- Cierre
-- Numero de Transacciones:60
-- Id proceso
-- Numero de regla


SELECT Oper.OPERCNTRID
     , CONTPROM
     , NUMTRANS
     , Oper.NUMPOLIZACNTR
     , Oper.TIPODOCUMENTOID
     , Oper.TIPOOPERACIONID
     , Oper.INSTRMONETARIOID
     , Oper.MONEDAID
     , Oper.CONTRATANTEID
     , Oper.AGENTEID
     , Oper.EMPLEADOID
     , Oper.SUCURSALID
     , Oper.PRODUCTOID
     , Oper.FECHAOPERACIONCNTR
     , Oper.LINEANEGOCIOID
     , Oper.MONTOMNCNTR
     , Oper.MONTOCNTR
     , Oper.MONTO_EFECTIVO
     , Cnte.CONTRATANTERFC
     , Oper.CODOPER
FROM (
    SELECT Oper2.OPERCNTRID
         , Oper2.NUMPOLIZACNTR
         , Oper2.TIPODOCUMENTOID
         , Oper2.TIPOOPERACIONID
         , Oper2.INSTRMONETARIOID
         , Oper2.MONEDAID
         , Oper2.CONTRATANTEID
         , Oper2.AGENTEID
         , Oper2.EMPLEADOID
         , Oper2.SUCURSALID
         , Oper2.PRODUCTOID
         , Oper2.FECHAOPERACIONCNTR
         , Oper2.LINEANEGOCIOID
         , Oper2.MONTOMNCNTR
         , Oper2.MONTOCNTR
         , Oper2.MONTO_EFECTIVO
         , Oper2.CODOPER
         -- Suma del numero de registros
--          , (SELECT sum(REGISTROS)
         -- Realiando el ajuste de la Ana agregamos la división para
         , (SELECT sum(REGISTROS)
            FROM ( --  Parametro de porcentaje en este caso 1.5% -- Se elimina el parametro
                     SELECT CONVERT(Char(8), OPE.FECHAOPERACIONCNTR, 112) AS FECHA,
                            COUNT(1)                                         Registros -- Cuenta los registros de los últimos 30 dias a partir de la fecha de operación anlizada
                     FROM SOFOM.MTS_HOPERACIONESCNTR OPE
                          -- Oper2 trae información de la operación analizada
                          -- Ope información contra los registros a analizar
                     WHERE OPE.FECHAOPERACIONCNTR < OPER2.FECHAOPERACIONCNTR
                       AND OPE.FECHAOPERACIONCNTR >=
                           DATEADD(DAY, -@NUM_DIAS_ANALISIS, OPER2.FECHAOPERACIONCNTR) -- 30 es por parametro
                       AND OPE.CONTRATANTEID = Oper2.CONTRATANTEID
                       AND OPE.TIPOOPERACIONID = @TIPO_OPERACION                       -- Se agrega tipo de operación de entrada
                       AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
                     Group by CONVERT(Char(8), OPE.FECHAOPERACIONCNTR, 112)) Rgs) CONTPROM
         -- Cuneta el número de registros sumados
         , (SELECT COUNT(1)
            FROM SOFOM.MTS_HOPERACIONESCNTR OPE
                 --[MARS] Con esta validación solo se estaran considerando operaciones con la misma fecha de la operación que se esta analizando
            WHERE Cast(OPE.FECHAOPERACIONCNTR as date) =
                  cast(OPER2.FECHAOPERACIONCNTR as date)                       -- CS se modifica para  considerar solo la parte de fecha
              --WHERE OPE.FECHAOPERACIONCNTR = OPER2.FECHAOPERACIONCNTR            --Se Cambian las fechas por fecha de ejecución
              AND month(OPE.FECHAOPERACIONCNTR) >= month(CIE.FECHA_FIN_CIERRE) -- Cambian las fechas por inicio de mes
              AND OPE.TIPOOPERACIONID = @TIPO_OPERACION                        -- Se agrega tipo de operación de entrada
              AND (OPE.CVE_ESTATUS = 'S' OR OPE.CVE_ESTATUS IS NULL)
              AND OPE.CONTRATANTEID = Oper2.CONTRATANTEID)                        NUMTRANS
    FROM SOFOM.MTS_HOPERACIONESCNTR OPER2,
         SOFOM.MTS_CRN_CIERRE CIE
    WHERE CIE.CIERREID = @ID_CIERRE               -- Parametro Cierre
      AND (OPER2.CVE_ESTATUS = 'S' OR OPER2.CVE_ESTATUS IS NULL)
      AND OPER2.TIPOOPERACIONID = @TIPO_OPERACION -- Se agrega tipo de operación de entrada
      AND OPER2.FECHAOPERACIONCNTR <= CIE.FECHA_FIN_CIERRE
      AND OPER2.FECHAOPERACIONCNTR >= CIE.FECHA_INI_CIERRE) Oper
   , SOFOM.MTS_DCONTRATANTE Cnte
WHERE Oper.CONTRATANTEID = Cnte.CONTRATANTEID
  AND Oper.CONTPROM IS NOT NULL
  AND Oper.NUMTRANS >= Oper.CONTPROM
  AND Oper.NUMTRANS >= @NUM_TRANSACCIONES_PERMITIDAS -- Parametro Numero de Transacciones
  AND NOT EXISTS(SELECT NULL
                 FROM SOFOM.MTS_HRN_CASOS_REGLAS
                 WHERE CODOPER = Oper.CODOPER
                   AND REGLANEGOCIOID = @REGLA_ID)   -- Numero de Regla
Order By Oper.CONTRATANTEID, Oper.FECHAOPERACIONCNTR, Oper.OPERCNTRID


-- SELECT OPER.OPERCNTRID
--      , OPER.CONTRATANTECD
--      , OPER.NUMPOLIZACNTR
--      , OPER.TIPODOCUMENTOID
--      , OPER.TIPOOPERACIONID
--      , OPER.INSTRMONETARIOID
--      , OPER.MONEDAID
--      , OPER.CONTRATANTEID
--      , OPER.AGENTEID
--      , OPER.EMPLEADOID
--      , OPER.SUCURSALID
--      , OPER.PRODUCTOID
--      , OPER.FECHAOPERACIONCNTR
--      , OPER.LINEANEGOCIOID
--      , OPER.MONTOMNCNTR
--      , OPER.MONTOCNTR
--      , OPER.MONTO_EFECTIVO -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
--      , OPER.CONTRATANTECD          CONTRATANTERFC
--      , OPER.CODOPER
--      , ISNULL(OPER.MONTOUSD, 0) AS MONTOUSD
-- FROM SOFOM.MTS_HOPERACIONESCNTR OPER,
--      (SELECT OPE.CONTRATANTECD,
--              CNT.CONTRATANTEID,
--              SUM(OPE.MONTOUSD)   MONTO_USD,
-- --SUM(OPE.MONTOCNTR) MONTO_PESOS,
--              MAX(OPE.OPERCNTRID) OPERCNTRID,
--              COUNT(OPE.CODOPER)  NUM_OPERACIONES
--       FROM SOFOM.MTS_HOPERACIONESCNTR OPE,
--            SOFOM.MTS_DCONTRATANTE CNT
--       WHERE 1 = 1
--         AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) BETWEEN '2020-05-27' AND '2020-06-27'
-- --AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) >= '2020-05-27' AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) <= '2020-06-27'
--         AND CNT.CONTRATANTEID = OPE.CONTRATANTEID
--         AND CNT.TIPOPERSONAFISCALID IN (2, 104)
--         AND RIGHT('00' + OPE.INSTRMONETARIOID, 2) IN ('03') -- PARAMETRO INSTRUMENTO MONETARIO EFECTIVO
--         AND RIGHT('00' + OPE.TIPOOPERACIONID, 2) IN ('01', '02')
--       GROUP BY OPE.CONTRATANTECD, CNT.CONTRATANTEID
--       HAVING SUM(OPE.MONTOUSD) >= 333333.33
--      ) OPERD
-- WHERE OPER.OPERCNTRID = OPERD.OPERCNTRID;


-- Query proporcionada por Hugo
SELECT OPER.OPERCNTRID
     , OPER.CONTRATANTECD
     , OPER.NUMPOLIZACNTR
     , OPER.TIPODOCUMENTOID
     , OPER.TIPOOPERACIONID
     , OPER.INSTRMONETARIOID
     , OPER.MONEDAID
     , OPER.CONTRATANTEID
     , OPER.AGENTEID
     , OPER.EMPLEADOID
     , OPER.SUCURSALID
     , OPER.PRODUCTOID
     , OPER.FECHAOPERACIONCNTR
     , OPER.LINEANEGOCIOID
     , OPER.MONTOMNCNTR
     , OPER.MONTOCNTR
     , OPER.MONTO_EFECTIVO -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
     , OPER.CONTRATANTECD          CONTRATANTERFC
     , OPER.CODOPER
     , ISNULL(OPER.MONTOUSD, 0) AS MONTOUSD
     , NUM_OPERACIONES
     , MONTO_USD
     , MONTO_CNTR
     , OPER.CUENTA_BENEFICIARIO
FROM SOFOM.MTS_HOPERACIONESCNTR OPER,
     (SELECT OPE.CONTRATANTECD,
             CNT.CONTRATANTEID,
             SUM(OPE.MONTOUSD)  MONTO_USD,
             sum(OPE.MONTOCNTR) MONTO_CNTR,
             OPE.CUENTA_BENEFICIARIO,
             OPE.CUENTA_ORDENANTE,
--SUM(OPE.MONTOCNTR) MONTO_PESOS,
             (SELECT MAX(OPERCNTRID)
              FROM SOFOM.MTS_HOPERACIONESCNTR OP
              WHERE OP.CONTRATANTEID = CNT.CONTRATANTEID
                AND CONVERT(VARCHAR, OP.FECHAOPERACIONCNTR, 23) BETWEEN '2020-07-02' AND '2020-07-03'
--AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) >= '2020-05-27' AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) <= '2020-06-27'
--AND CONTRATANTEID = 284 -- OPERCNTRID = 5265885
                AND RIGHT('00' + OP.INSTRMONETARIOID, 2) IN ('03') -- PARAMETRO INSTRUMENTO MONETARIO EFECTIVO
                AND RIGHT('00' + OP.TIPOOPERACIONID, 2) IN ('01', '02')
             )                  OPERCNTRID,
             COUNT(OPE.CODOPER) NUM_OPERACIONES
      FROM SOFOM.MTS_HOPERACIONESCNTR OPE,
           SOFOM.MTS_DCONTRATANTE CNT
      WHERE 1 = 1
        AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) BETWEEN '2020-07-02' AND '2020-07-03'
--AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) >= '2020-05-27' AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) <= '2020-06-27'
        AND CNT.CONTRATANTEID = OPE.CONTRATANTEID
--AND CNT.CONTRATANTEID = 284 -- OPERCNTRID = 5265885
--         AND CNT.TIPOPERSONAFISCALID IN (104, 2, 103)             -- Pesonas morales
        AND CNT.TIPOPERSONAFISCALID IN (103)             -- Pesonas morales
--         AND CNT.TIPOPERSONAFISCALID IN (2, 104) -- Pesonas morales
--         AND CNT.TIPOPERSONAFISCALID = 103
        AND RIGHT('00' + OPE.INSTRMONETARIOID, 2) IN ('03') -- PARAMETRO INSTRUMENTO MONETARIO EFECTIVO
        AND RIGHT('00' + OPE.TIPOOPERACIONID, 2) IN ('01', '02')
      GROUP BY OPE.CONTRATANTECD, CNT.CONTRATANTEID, OPE.CUENTA_BENEFICIARIO, CUENTA_ORDENANTE
--       HAVING SUM(OPE.MONTOUSD) >= 1000
--       HAVING SUM(OPE.MONTOUSD) >= 333333.33
--       HAVING SUM(OPE.MONTOCNTR) >= 20000
      HAVING SUM(OPE.MONTOCNTR) >= 7000000
     ) OPERD
WHERE OPER.OPERCNTRID = OPERD.OPERCNTRID;




--
SELECT COUNT(*)       CONTADORR,
       OPE.CONTRATANTECD,
       SUM(MONTOUSD)  MONTO_USD,
       SUM(MONTOCNTR) MONTO_PESOS,
       COUNT(CODOPER) NUM_OPERACIONES,
       OPE.CUENTA_ORDENANTE,
       OPE.CUENTA_BENEFICIARIO
FROM SOFOM.MTS_HOPERACIONESCNTR OPE
WHERE 1 = 1
  AND CONVERT(VARCHAR, OPE.FECHAOPERACIONCNTR, 23) BETWEEN '2020-07-02' AND '2020-07-03'
GROUP BY OPE.CONTRATANTECD, OPE.CUENTA_ORDENANTE, OPE.CUENTA_BENEFICIARIO
HAVING SUM(MONTOCNTR) >= 7000000
ORDER BY MONTO_USD DESC;



-- IFN060425C53
-- 74511606.43
-- OPERCNTRID,CONTRATANTECD,NUMPOLIZACNTR,TIPODOCUMENTOID,TIPOOPERACIONID,INSTRMONETARIOID,MONEDAID,CONTRATANTEID,AGENTEID,EMPLEADOID,SUCURSALID,PRODUCTOID,FECHAOPERACIONCNTR,LINEANEGOCIOID,MONTOMNCNTR,MONTOCNTR,MONTO_EFECTIVO,CONTRATANTERFC,CODOPER,MONTOUSD,NUM_OPERACIONES,MONTO_USD,MONTO_CNTR
-- 5385786,IFN060425C53,,,01,3,MXN,2846356,,,1,,2020-06-29 14:25:18,,74511606.43,74511606.43,,IFN060425C53,21325596R,3268583.34,3,3955214.28,90164251.33
select OPER.OPERCNTRID
     , OPER.CONTRATANTECD
     , OPER.NUMPOLIZACNTR
     , OPER.TIPODOCUMENTOID
     , OPER.TIPOOPERACIONID
     , OPER.INSTRMONETARIOID
     , OPER.MONEDAID
     , OPER.CONTRATANTEID
     , OPER.AGENTEID
     , OPER.EMPLEADOID
     , OPER.SUCURSALID
     , OPER.PRODUCTOID
     , OPER.FECHAOPERACIONCNTR
     , OPER.LINEANEGOCIOID
     , OPER.MONTOMNCNTR
     , OPER.MONTOCNTR
     , OPER.MONTO_EFECTIVO -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
     , OPER.CONTRATANTECD CONTRATANTERFC
     , OPER.CODOPER
     , CUENTA_BENEFICIARIO
from SOFOM.MTS_HOPERACIONESCNTR OPER
where 1 = 1
  AND CONVERT(VARCHAR, OPER.FECHAOPERACIONCNTR, 23) BETWEEN '2020-06-28' AND '2020-06-29'
  and CONTRATANTECD = 'BIT140123U70'
group by CUENTA_BENEFICIARIO


select                     -- COUNT(1)
    OPER.OPERCNTRID
     , OPER.CONTRATANTECD
     , OPER.NUMPOLIZACNTR
     , OPER.TIPODOCUMENTOID
     , OPER.TIPOOPERACIONID
     , OPER.INSTRMONETARIOID
     , OPER.MONEDAID
     , OPER.CONTRATANTEID
     , OPER.AGENTEID
     , OPER.EMPLEADOID
     , OPER.SUCURSALID
     , OPER.PRODUCTOID
     , OPER.FECHAOPERACIONCNTR
     , OPER.LINEANEGOCIOID
     , OPER.MONTOMNCNTR
     , OPER.MONTOCNTR
     , OPER.MONTO_EFECTIVO -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
     , OPER.CONTRATANTECD CONTRATANTERFC
     , OPER.CODOPER
     , OPER.CUENTA_BENEFICIARIO
     , MONTO_MX
     , MONTO_USD
FROM SOFOM.MTS_HOPERACIONESCNTR OPER,
     (
         -- Primero hacemos la query que agrupe las cuentas por la cuenta del beneficiario en donde esta agrupación
         -- supere un monto de 7millones
         select sum(MONTOUSD)  MONTO_USD,
                sum(MONTOCNTR) MONTO_MX,
                CUENTA_BENEFICIARIO,
                CONTRATANTECD
         from SOFOM.MTS_HOPERACIONESCNTR OPER
         where 1 = 1
           AND CONVERT(VARCHAR, OPER.FECHAOPERACIONCNTR, 23) BETWEEN '2020-06-28' AND '2020-06-29'
           and CONTRATANTECD = 'BIT140123U70'
         group by CUENTA_BENEFICIARIO, CONTRATANTECD
         HAVING SUM(MONTOCNTR) > 7000000) OPER_TMP
-- Filtramos información por el los datos del contratante y los cuentas de los Beneficarios
WHERE OPER.CONTRATANTECD = OPER_TMP.CONTRATANTECD
  and OPER.CUENTA_BENEFICIARIO = OPER_TMP.CUENTA_BENEFICIARIO;


-- Ahora seleccionamos los campos del contratante que necesitamos
-- Falta la discriminación de que la suma de 700000 sea superada donde la cuenta beneficiario sea la misma
-- En el segundo paso al recuperar todas las transacciones que con la misma cuenta beneficiario sume los 700000

select DATEADD(DAY, -1, current_timestamp)
--  2 - 104 - 103[Fisicas]


select *
--        OPER.OPERCNTRID
--      , OPER.CONTRATANTECD
--      , OPER.NUMPOLIZACNTR
--      , OPER.TIPODOCUMENTOID
--      , OPER.TIPOOPERACIONID
--      , OPER.INSTRMONETARIOID
--      , OPER.MONEDAID
--      , OPER.CONTRATANTEID
--      , OPER.AGENTEID
--      , OPER.EMPLEADOID
--      , OPER.SUCURSALID
--      , OPER.PRODUCTOID
--      , OPER.FECHAOPERACIONCNTR
--      , OPER.LINEANEGOCIOID
--      , OPER.MONTOMNCNTR
--      , OPER.MONTOCNTR
--      , OPER.MONTO_EFECTIVO -- CONSIDERA ESTA COLUMNA QUE ESTÁ EN PESOS PERO AQUÍ SE HACE LA CONVERSIÓN A USD
--      , OPER.CONTRATANTECD          CONTRATANTERFC
--      , OPER.CODOPER
from SOFOM.MTS_HOPERACIONESCNTR OPER
where 1 = 1
  AND CONVERT(VARCHAR, OPER.FECHAOPERACIONCNTR, 23) BETWEEN '2020-06-28' AND '2020-06-29'
  and CONTRATANTECD IN ('RIVL770321HNEVVS06')


SELECT *
-- COUNT(CODOPER) NUM_OPERACIONES
FROM SOFOM.MTS_HOPERACIONESCNTR
WHERE 1=1
AND CONTRATANTECD = 'XEXX010101000'
AND CONVERT(VARCHAR, FECHAOPERACIONCNTR, 23) BETWEEN '2020-07-01' AND '2020-07-03';


-- 621,221,250.56


