-- RN32 INVERSIÓN INICIAL NO ACORDÉ A LOS INGRESOS Y ACTIVIDAD

DECLARE @TIPO_OPERACION AS VARCHAR = ''
DECLARE @ID_CIERRE AS VARCHAR = ?;
DECLARE @ID_REGLA AS INT = ?;

SELECT OPER.OPERCNTRID,
       OPER.NUMPOLIZACNTR,
       OPER.TIPODOCUMENTOID,
       OPER.TIPOOPERACIONID,
       OPER.INSTRMONETARIOID,
       OPER.MONEDAID,
       OPER.CONTRATANTEID,
       OPER.AGENTEID,
       OPER.EMPLEADOID,
       OPER.SUCURSALID,
       OPER.PRODUCTOID,
       OPER.FECHAOPERACIONCNTR,
       OPER.LINEANEGOCIOID,
       OPER.MONTOMNCNTR, -- ESTE ES EL MONTO A CONSIDERAR ESPRESADO EN USD,OPER.MONTOCNTR,OPER.MONTO_EFECTIVO,CNTE.CONTRATANTERFC,OPER.CODOPER
OPER.MONTOUSD -- [MARS] Se agrega parámetro - 28-jun-2020
FROM [SOFOM].MTS_HOPERACIONESCNTR OPER,
     [SOFOM].MTS_DCONTRATANTE CNTE,
     [SOFOM].MTS_CRN_CIERRE CIER
WHERE OPER.CONTRATANTEID = CNTE.CONTRATANTEID
  AND CIER.CIERREID = @ID_CIERRE                   -- PARAMETRO CIERRE
  AND OPER.FECHAOPERACIONCNTR <= CIER.FECHA_FIN_CIERRE
  AND OPER.FECHAOPERACIONCNTR >= CIER.FECHA_INI_CIERRE
  AND RIGHT('00' + OPER.TIPOOPERACIONID, 2) IN (@TIPO_OPERACION)
  AND OPER.MONTOMNCNTR > CNTE.CONTRATANTEINGRESOS
  AND (OPER.CVE_ESTATUS = 'S' OR OPER.CVE_ESTATUS IS NULL)
  AND NOT EXISTS(SELECT NULL
                 FROM [SOFOM].MTS_HRN_CASOS
                 WHERE CODOPER = OPER.CODOPER
                   AND REGLANEGOCIOID = @ID_REGLA) --PARÁMETRO
ORDER BY OPER.CONTRATANTEID, OPER.FECHAOPERACIONCNTR, OPER.OPERCNTRID