-- Versión modificada por emmanuel 03/07/2020
/**************************************************************************
REGLA 243
Alerta de Inusualidad - Cambio en el Perfil Transaccional
- Suma todos los montos de las operaciones en un mes calendario y los compara con el perfil transaccional declarado del cliente
  para riesgo bajo.
  Donde el perfil transaccional es

-- NOTAS:
El valor PORCENT_* se recupera de del porcentaje de la tabla [mts_hrn_parametros] dependiendo de la regla a
ejecutar este caso la 243
***************************************************************************/
DECLARE @YEAR INT = 2020;
DECLARE @MONTH INT = 3;
DECLARE @ROL VARCHAR(2) = 'CL';
DECLARE @TIPO_PERSONA NVARCHAR(100) = '1,2,3,4,,'
select @TIPO_PERSONA;
DECLARE @PORCENT_NUM_OPERACIONES FLOAT = 1.30;
DECLARE @PORCENT_MONTO_TRX FLOAT = 1.30;
DECLARE @PORCENT_NO_PAGOS FLOAT = 1.30;
DECLARE @NIVEL_RIESGO VARCHAR(2) = 'A';


SELECT @YEAR    ANIO,
       @MONTH   MES,
       KPER.CONTRATANTECD,
       KPER.CVE_ROL,
       KPER.NOMBRES,
       KPER.APELLIDO_PATERNO,
       KPER.APELLIDO_MATERNO,
       KPER.DS_RAZON_SOCIAL,
       KPER.CURP,
       KPER.RFC CONTRATANTERFC,
       KPER.CVE_TIPO_FISICA_MORAL,
       KPER.CVE_NIVEL_RIESGO,
       NO_OPERACIONES_DEPOSITO,
       CONTRATANTEID,
       INSTRMONETARIOID,
       SUCURSALID,
       MONEDAID,
       AGENTEID,
       TIPOOPERACIONID,
       NUMPOLIZACNTR,
       FECHAOPERACIONCNTR,
       OPERCNTRID,
       PRODUCTOID,
       TIPODOCUMENTOID,
       EMPLEADOID,
       LINEANEGOCIOID,
       MONTOMNCNTR,
       MONTOCNTR,
       MONTO_EFECTIVO,
       CODOPER,
       ACT_NO_TOT_DEPOSITOS,
       IMP_MONTO_ESTIMADO_TRX_DEPOSITO,
       ACT_IMP_MONTO_TOT_DEPOSITOS,
       NO_OPERACIONES_RETIRO,
       ACT_NO_TOT_RETIROS,
       IMP_MONTO_ESTIMADO_TRX_RETIRO,
       ACT_IMP_MONTO_TOT_RETIROS,
       NO_PAGOS_CREDITO_MENSUAL,
       ACT_NO_TOT_APORTACIONES,
       IMP_MONTO_PAGOS_CREDITO_MENSUAL,
       ACT_IMP_MONTO_TOT_APORTACIONES
       --PERFIL. SELECT *
FROM SOFOM.MTS_VL_KYC_ANALISIS_PERFIL PERFIL,
     SOFOM.MTS_VL_KYC_PERSONAS KPER
WHERE YEAR = @YEAR /* SE OBTIENE A PARTIR DE LA FECHA FIN DE CIERRE */
  AND MONTH = @MONTH/*  SE OBTIENE A PARTIR DE LA FECHA FIN DE CIERRE */
  AND KPER.CONTRATANTECD = PERFIL.CONTRATANTECD
  AND KPER.CVE_ROL = @ROL
  AND KPER.CVE_TIPO_FISICA_MORAL IN (@TIPO_PERSONA)       -- -- PARAMETRO DE TIPO DE PERSONAS
  AND CHARINDEX(KPER.CVE_NIVEL_RIESGO, @NIVEL_RIESGO) > 0 -- PARAMETO NIVEL DE RIESGO
  AND ((((CAST(NO_OPERACIONES_DEPOSITO AS DECIMAL) * (@PORCENT_NUM_OPERACIONES)) - ACT_NO_TOT_DEPOSITOS) < 0 AND
        NO_OPERACIONES_DEPOSITO > 0) OR
       (((CAST(IMP_MONTO_ESTIMADO_TRX_DEPOSITO AS DECIMAL) * (@PORCENT_MONTO_TRX)) - ACT_IMP_MONTO_TOT_DEPOSITOS) <
        0 AND
        IMP_MONTO_ESTIMADO_TRX_DEPOSITO > 0) OR
       (((CAST(NO_OPERACIONES_RETIRO AS DECIMAL) * (@PORCENT_NUM_OPERACIONES)) - ACT_NO_TOT_RETIROS) < 0 AND
        NO_OPERACIONES_RETIRO > 0) OR
       (((CAST(IMP_MONTO_ESTIMADO_TRX_RETIRO AS DECIMAL) * (@PORCENT_MONTO_TRX)) - ACT_IMP_MONTO_TOT_RETIROS) < 0 AND
        IMP_MONTO_ESTIMADO_TRX_RETIRO > 0) OR
    -- Se comento una vez con @Orlando y Luis estas condiciones quedaban fuera. [???]
       (((CAST(NO_PAGOS_CREDITO_MENSUAL AS DECIMAL) * (@PORCENT_NO_PAGOS)) - ACT_NO_TOT_APORTACIONES) < 0 AND
        NO_PAGOS_CREDITO_MENSUAL > 0) OR
       (((CAST(IMP_MONTO_PAGOS_CREDITO_MENSUAL AS DECIMAL) * (@PORCENT_NO_PAGOS)) - ACT_IMP_MONTO_TOT_APORTACIONES) <
        0 AND IMP_MONTO_PAGOS_CREDITO_MENSUAL > 0));




SELECT REGLANEGOCIOID,
       PARAMETROID,
       DESCRIPCION_PARAMETRO,
       VALOR,
       FECHA_ACTUALIZACION,
       USUARIO,
       NOMBRE_PARAMETRO_REGLA,
       CVE_PARAMETRO_REGLA,
       VIGENCIA
FROM [SOFOM].MTS_HRN_PARAMETROS
WHERE REGLANEGOCIOID = 243;



