SELECT OP.OPERCNTRID,
     OP.NUMPOLIZACNTR,
     OP.TIPODOCUMENTOID,
     OP.TIPOOPERACIONID,
     OP.INSTRMONETARIOID,
     OP.MONEDAID,
     OP.CONTRATANTEID,
     OP.AGENTEID,
     OP.EMPLEADOID,
     OP.SUCURSALID,
     OP.PRODUCTOID,
     OP.FECHAOPERACIONCNTR,
     OP.LINEANEGOCIOID,
     OP.MONTOMNCNTR,
     OP.MONTOCNTR,
     OP.MONTO_EFECTIVO,
     OP.CONTRATANTECD          CONTRATANTERFC,
     OP.CODOPER,
     ISNULL(OP.MONTOUSD, 0) AS MONTOUSD,
     PIVOTE.NUM_OPERACIONES,
     PIVOTE.MONTOUSD_TOTAL,
     PIVOTE.MONTOMN_TOTAL,
     OP.CUENTA_BENEFICIARIO,
     OP.CUENTA_ORDENANTE
FROM [schema].MTS_HOPERACIONESCNTR OP,
(
     SELECT MAX(OPERCNTRID)  OPERCNTRID,
               OPE.CONTRATANTEID,
               COUNT(*)         NUM_OPERACIONES,
               SUM(MONTOMNCNTR) MONTOMN_TOTAL,
               SUM(MONTOUSD)    MONTOUSD_TOTAL
     FROM (SELECT OPERCNTRID, CONTRATANTEID, MONTOMNCNTR, MONTOUSD
          FROM [schema].MTS_HOPERACIONESCNTR WITH (INDEX ([IDX_FECHAOPERACION]))
          WHERE FECHAOPERACIONCNTR BETWEEN ? AND ? -- <1>
               AND CHARINDEX(INSTRMONETARIOID, ?) > 0 -- <2>
               AND CHARINDEX(TIPOOPERACIONID, ?) > 0 -- <3>
               AND CHARINDEX(CVE_TIPO_ORDEN, ?) > 0 -- <4>
          ) OPE
               JOIN [schema].MTS_DCONTRATANTE CNT
                    ON CNT.CONTRATANTEID = OPE.CONTRATANTEID AND
                         CHARINDEX(CAST(CNT.TIPOPERSONAFISCALID AS VARCHAR), ?) > 0 -- <5>
     GROUP BY OPE.CONTRATANTEID
     HAVING SUM(OPE.MONTOMNCNTR) > ? -- <6>
) PIVOTE
WHERE OP.OPERCNTRID = PIVOTE.OPERCNTRID
AND NOT EXISTS(SELECT NULL
               FROM [schema].MTS_HRN_CASOS_REGLAS
               WHERE CODOPER = OP.CODOPER
               AND REGLANEGOCIOID = ?) -- <7>
ORDER BY OP.CONTRATANTEID